title = "Jackson Heights Orchestra"
baseURL = "https://jhorchestra.org"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
Copyright = "Jackson Heights Orchestra"

[languages]
  [languages.en]
    title = "Jackson Heights Orchestra"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

# Is this necessary?
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The Premiere Orchestra in Jackson Heights, Queens"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "youtube",
  "facebook",
  "instagram",
  "twitter",
]

[params.ananke.social.follow]
networks = [
  "youtube",
  "facebook",
  "instagram",
  "twitter",
]

[params.ananke.social.youtube]
username = "JacksonHeightsOrchestra"
profilelink = "https://www.youtube.com/channel/UCJulQspTGCpaDdx2wKYfFvQ"

[params.ananke.social.facebook]
username = "JacksonHeightsOrchestra"

[params.ananke.social.instagram]
username = "jhorchestra"

[params.ananke.social.twitter]
username = "jhorchestra"
